on:
  push:
    branches:
    - release
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.14.1
